version: "3"
services:
  app:
    build:
      context: "./docker/app/"
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html"
      - "./docker/app/apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf"
      
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
