version: "3"
services:
  app:
    build:
      context: "./docker/app/"
    ports:
      - "80:80"
    volumes:
      - "./www/:/var/www/html"
      - "./docker/app/apache2/apache2.conf:/etc/apache2/apache2.conf"
      - "./docker/app/apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf"

    depends_on:
      - postgres
  postgres:
    build:
      context: "./docker/postgres/"
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pass
    volumes:
      - "./docker/postgres/initdb:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
